<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="2" ignored="0" total="6" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="TestNGLearning suite" duration-ms="91" started-at="2019-04-30T22:40:53Z" finished-at="2019-04-30T22:40:53Z">
    <groups>
    </groups>
    <test name="Login test" duration-ms="35" started-at="2019-04-30T22:40:53Z" finished-at="2019-04-30T22:40:53Z">
      <class name="testCases.TestCase1">
        <test-method status="PASS" signature="DBConn()[pri:0, instance:testCases.TestCase1@58651fd0]" name="DBConn" is-config="true" duration-ms="10" started-at="2019-04-30T22:40:53Z" finished-at="2019-04-30T22:40:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DBConn -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:testCases.TestCase1@58651fd0]" name="launchBrowser" is-config="true" duration-ms="0" started-at="2019-04-30T22:40:53Z" finished-at="2019-04-30T22:40:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="doRegistration()[pri:1, instance:testCases.TestCase1@58651fd0]" name="doRegistration" duration-ms="4" started-at="2019-04-30T22:40:53Z" finished-at="2019-04-30T22:40:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doRegistration -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:testCases.TestCase1@58651fd0]" name="closeBrowser" is-config="true" duration-ms="0" started-at="2019-04-30T22:40:53Z" finished-at="2019-04-30T22:40:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="doLogin()[pri:2, instance:testCases.TestCase1@58651fd0]" name="doLogin" duration-ms="1" started-at="2019-04-30T22:40:53Z" finished-at="2019-04-30T22:40:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:testCases.TestCase1@58651fd0]" name="launchBrowser" is-config="true" duration-ms="0" started-at="2019-04-30T22:40:53Z" finished-at="2019-04-30T22:40:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="DBDisconn()[pri:0, instance:testCases.TestCase1@58651fd0]" name="DBDisconn" is-config="true" duration-ms="0" started-at="2019-04-30T22:40:53Z" finished-at="2019-04-30T22:40:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DBDisconn -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:testCases.TestCase1@58651fd0]" name="closeBrowser" is-config="true" duration-ms="0" started-at="2019-04-30T22:40:53Z" finished-at="2019-04-30T22:40:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- testCases.TestCase1 -->
    </test> <!-- Login test -->
    <test name="Title verification" duration-ms="10" started-at="2019-04-30T22:40:53Z" finished-at="2019-04-30T22:40:53Z">
      <class name="testCases.TestCase2">
        <test-method status="FAIL" signature="doVerification()[pri:0, instance:testCases.TestCase2@d8355a8]" name="doVerification" duration-ms="6" started-at="2019-04-30T22:40:53Z" finished-at="2019-04-30T22:40:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [false] but found [true],
expected [true] but found [false],
expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true],
expected [true] but found [false],
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at testCases.TestCase2.doVerification(TestCase2.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doVerification -->
      </class> <!-- testCases.TestCase2 -->
    </test> <!-- Title verification -->
    <test name="Dependency test" duration-ms="6" started-at="2019-04-30T22:40:53Z" finished-at="2019-04-30T22:40:53Z">
      <class name="testCases.TestCase3">
        <test-method status="FAIL" signature="doRegistration()[pri:0, instance:testCases.TestCase3@3ffc5af1]" name="doRegistration" duration-ms="0" started-at="2019-04-30T22:40:53Z" finished-at="2019-04-30T22:40:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Registration failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Registration failed
at org.testng.Assert.fail(Assert.java:96)
at testCases.TestCase3.doRegistration(TestCase3.java:11)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doRegistration -->
        <test-method status="SKIP" signature="doLogin()[pri:0, instance:testCases.TestCase3@3ffc5af1]" name="doLogin" duration-ms="0" started-at="2019-04-30T22:40:53Z" depends-on-methods="testCases.TestCase3.doRegistration" finished-at="2019-04-30T22:40:53Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestCase3.doLogin()[pri:0, instance:testCases.TestCase3@3ffc5af1] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestCase3.doLogin()[pri:0, instance:testCases.TestCase3@3ffc5af1] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="thirdTest()[pri:0, instance:testCases.TestCase3@3ffc5af1]" name="thirdTest" duration-ms="1" started-at="2019-04-30T22:40:53Z" depends-on-methods="testCases.TestCase3.doLogin, testCases.TestCase3.doRegistration" finished-at="2019-04-30T22:40:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- thirdTest -->
      </class> <!-- testCases.TestCase3 -->
    </test> <!-- Dependency test -->
  </suite> <!-- TestNGLearning suite -->
</testng-results>
